Sequential Numbers = GENERATESERIES(1, 20, 1)
---------------------------------------------
Sequential Numbers =
SELECTCOLUMNS(
    GENERATESERIES(1, 20, 1)
    , "ID"
    , [Value]
    )
---------------------------------------------
Orders with List Price Bigger than or Equal to $1,000 =
CALCULATE(
    SUM('Internet Sales'[OrderQuantity])
        , FILTER('Product' //Virtual table start
            , 'Product'[List Price]>=1000
                ) //Virtual table end
        )
---------------------------------------------
Order Qty for Customers Buying More than 4 Product with List Price Bigger Than $1,000 =
SUMX(
    FILTER(
        VALUES(Customer[CustomerKey]) //Virtual table
        , [Orders with List Price Bigger than or Equal $1,000] > 4
        )
    , [Orders with List Price Bigger than or Equal $1,000]
    )
---------------------------------------------
Test Virtual Table =
FILTER('Product'//Virtual table start
            , 'Product'[List Price]>=1000
                ) //Virtual table end
---------------------------------------------
EVALUATE
FILTER('Product' //Virtual table start
            , 'Product'[List Price]>=1000
                ) //Virtual table end    
---------------------------------------------                
Avg. Product Standard Costs =
AVERAGE('Internet Sales'[ProductStandardCost])
---------------------------------------------
Avg. Product Standard Costs Correct =
AVERAGEX(
    SUMMARISE (
        'Internet Sales'
        , 'Product'[ProductKey]
        ,  'Internet Sales'[ProductStandardCost]
        )
        , 'Internet Sales'[ProductStandardCost]
)
---------------------------------------------
Internet Sales USD =
SUMX(
    NATURALINNERJOIN (
            SELECTCOLUMNS(
                'Internet Sales'
, "CurrencyKeyJoin", 'Internet Sales'[CurrencyKey] * 1
                , "DateJoin", 'Internet Sales'[OrderDate] + 0
                , "ProductKey", 'Internet Sales'[ProductKey]
                , "SalesOrderLineNumber", 'Internet Sales'[SalesOrderLineNumber]
                , "SalesOrderNumber", 'Internet Sales'[SalesOrderNumber]
                , "SalesAmount", 'Internet Sales'[SalesAmount]
                )
            , SELECTCOLUMNS (
                'Exchange Rates'
                , "CurrencyKeyJoin", 'Exchange Rates'[CurrencyKey] * 1
                , "DateJoin", 'Exchange Rates'[Date] + 0
                , "AverageRate", 'Exchange Rates'[AverageRate]
            )
        )
, [AverageRate] * [SalesAmount]
)
---------------------------------------------
Internet Sales MTD =
TOTALMTD(
    [Internet Sales]
    , 'Date'[Full Date]
)
---------------------------------------------
Internet Sales LMTD =
TOTALMTD(
    [Internet Sales]
    , DATEADD('Date'[Full Date], -1, MONTH)
    )
---------------------------------------------
Internet Sales YTD =
TOTALYTD(
    [Internet Sales]
    , 'Date'[Full Date]
    )
---------------------------------------------
Internet Sales LYTD =
TOTALYTD (
    [Internet Sales]
    , DATEADD('Date'[Full Date], -1, YEAR)
)
---------------------------------------------
Internet Sales LY MTD =
TOTALMTD(
    [Internet Sales]
    , SAMEPERIODLASTYEAR('Date'[Full Date])
)
---------------------------------------------
Internet Sales MTD Blanking Invalid Dates =
VAR lastorderDate = MAX('Internet Sales'[OrderDateKey])
RETURN
IF(
    MAX('Date'[DateKey]) <= lastoderDate
    , TOTALMTD(
            [Internet Sales]
            , 'Date'[Full Date]
            )
    )
---------------------------------------------
IsValidDate =
    AND('Date'[DateKey] >= MIN('Internet Sales'[OrderDateKey])
        , 'Date'[DateKey] <= MAX('Internet Sales'[OrderDateKey])
    )
---------------------------------------------
Internet Sales MTD with Valid Dates =
TOTALMTD(
    [Internet Sales]
    , CALCULATETABLE(
        VALUES('Date'[Full Date])
        , 'Date'[IsValidDate] = TRUE()
    )
)
---------------------------------------------
Internet Sales LMTD with Valid Dates =
TOTALMTD(
    [Internet Sales]
    , DATEADD(
            CALCULATETABLE(
                    VALUES('Date'[Full Date])
                    , 'Date'[IsValidDate] = TRUE()
                    )
        , -1
        , MONTH
        )
    )
---------------------------------------------
Internet Sales YTD with Valid Dates =
CALCULATE(
    TOTALYTD(
        [Internet Sales]
        , CALCULATETABLE(
                    VALUES('Date'[Full Date])
                    , 'Date'[IsValidDate] = TRUE()
                    )
            ) 
)
---------------------------------------------
Internet Sales LYTD with Valid Dates =
TOTALYTD (
    [Internet Sales]
    , DATEADD(
            CALCULATETABLE(
                    VALUES('Date'[Full Date])
                    , 'Date'[IsValidDate] = true()
                )
            , -1
            , YEAR
            )
        )
---------------------------------------------
Internet Sales LY MTD with Valid Dates =
TOTALMTD(
    [Internet Sales]
    , SAMEPERIODLASTYEAR(
            CALCULATETABLE(
                VALUES('Date'[Full Date])
                , 'Date'[IsValidDate] = TRUE()
                    )
                )
            )
---------------------------------------------
Internet Sales MoM Variance = Internet Sales – Internet Sales LM
---------------------------------------------
Internet Sales YoY Variance = Internet Sales – Internet Sales LY
---------------------------------------------
Internet Sales LM =
CALCULATE(
        [Internet Sales]
        , DATEADD('Date'[Full Date], -1, MONTH)
)
---------------------------------------------
Internet Sales LY =
CALCULATE(
        [Internet Sales]
        , SAMEPERIODLASTYEAR('Date'[Full Date])
)
---------------------------------------------
Internet Sales MoM Variance = [Internet Sales] - [Internet Sales LM]
---------------------------------------------
Internet Sales MoM Variance Incorrect =
IF(
    NOT(ISBLANK([Internet Sales LM]))
    , [Internet Sales] - [Internet Sales LM]
    )
---------------------------------------------
Internet Sales MOM Variance =
VAR firstValidDateWithSalesLM = FIRSTNONBLANK(ALL('Date'[Full Date]), [Internet Sales LM])
VAR lastValidDateWithSalesLM = LASTNONBLANK(ALL('Date'[Full Date]), [Internet Sales])
RETURN
    SUMX(
        FILTER(
            VALUES('Date'[Full Date])
            , 'Date'[Full Date] >= firstValidDateWithSalesLM
                && 'Date'[Full Date] <= lastValidDateWithSalesLM
            )
        , [Internet Sales] - [Internet Sales LM]
        )
---------------------------------------------
Internet Sales YoY Variance =
VAR firstValidDateWithSalesLY = FIRSTNONBLANK(ALL('Date'[Full Date]), [Internet Sales LY])
VAR lastValidDateWithSalesLY = LASTNONBLANK(ALL('Date'[Full Date]), [Internet Sales])
RETURN
    SUMX(
        FILTER(
            VALUES('Date'[Full Date])
            , 'Date'[Full Date] >= firstValidDateWithSalesLY
                && 'Date'[Full Date] <= lastValidDateWithSalesLY
            )
        , [Internet Sales] - [Internet Sales LY])
---------------------------------------------
Date =
VAR firstOderDate = MIN('Internet Sales'[OrderDate])
VAR lastOderDate = MAX('Internet Sales'[OrderDate])
RETURN
ADDCOLUMNS(
    SELECTCOLUMNS(
            CALENDARAUTO()
            , "Full Date"
            , [Date]
            )
    , "DateKey", VALUE(FORMAT([Full Date], "yyyyMMdd"))
    , "Quarter", CONCATENATE("Q ", QUARTER([Full Date]))
    , "Month", FORMAT([Full Date], "MMMM")
    , "Month Short", FORMAT([Full Date], "MMM")
    , "MonthOrder", MONTH([Full Date])
    , "Week", CONCATENATE("Wk ", WEEKNUM([Full Date]))
    , "Day", FORMAT([Full Date], "dddd")
    , "Day Short", FORMAT([Full Date], "ddd")
    , "Day of Month", DAY([Full Date])
    , "DayOrder", WEEKDAY([Full Date], 2) //First day is Monday
    , "Year Month", FORMAT([Full Date], "yyyy-MM")
    , "IsValidDate", AND([Full Date] >= firstOderDate, [Full Date] <= lastOderDate)
)
---------------------------------------------
Internet Sales MTD =
TOTALMTD(
        [Internet Sales]
        , 'Date'[Full Date]
        )
---------------------------------------------
Internet Sales YTD =
TOTALYTD(
        [Internet Sales]
        , 'Date'[Full Date])
---------------------------------------------
Internet Sales LMTD=
TOTALMTD(
        [Internet Sales]
        , DATEADD('Date'[Full Date], -1, MONTH)
)
---------------------------------------------
Internet Sales LYTD =
TOTALYTD(
        [Internet Sales]
        , SAMEPERIODLASTYEAR('Date'[Full Date])
)
---------------------------------------------
Internet Sales MTD =
TOTALMTD(
        [Internet Sales]
        , 'Date'[Full Date]
        , ALL('Date')
        )
---------------------------------------------
Internet Sales YTD =
TOTALYTD(
        [Internet Sales]
        , 'Date'[Full Date]
        , ALL('Date')
        )
---------------------------------------------
Internet Sales LMTD =
TOTALYTD(
        [Internet Sales]
        , DATEADD('Date'[Full Date], -1, MONTH)
        , ALL('Date')
)
---------------------------------------------
Internet Sales LYTD =
TOTALYTD(
        [Internet Sales]
        , SAMEPERIODLASTYEAR('Date'[Full Date])
        , ALL('Date')
        )
---------------------------------------------
Order Time = TIMEVALUE(FORMAT([OrderDateTime], "hh:mm:ss"))
---------------------------------------------
Time =
SELECTCOLUMNS(
    GENERATESERIES(1/86400, 1, TIME(0, 0, 1))
    , "Time", [Value]
    , "Hour", HOUR ( [Value] )
    , "Minute", MINUTE ( [Value] )
    , "5 Min",  TIME(HOUR([Value]), FLOOR(MINUTE([Value])/5, 1) * 5, 0) + TIME(0, 5, 0)
    , "15 Min", TIME(HOUR([Value]), FLOOR(MINUTE([Value])/15, 1) * 15, 0) + TIME(0, 15, 0)
    , "30 Min", TIME(HOUR([Value]), FLOOR(MINUTE([Value])/30, 1) * 30, 0) + TIME(0, 30, 0)
    , "45 Min", TIME(HOUR([Value]), FLOOR(MINUTE([Value])/45, 1) * 45, 0) + TIME(0, 45, 0)
    , "60 Min", TIME(HOUR([Value]), FLOOR(MINUTE([Value])/60, 1) * 60, 0) + TIME(0, 60, 0)
)
